/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestRO } from './RequestRO';
import {
    RequestROFromJSON,
    RequestROFromJSONTyped,
    RequestROToJSON,
} from './RequestRO';
import type { ResponseRO } from './ResponseRO';
import {
    ResponseROFromJSON,
    ResponseROFromJSONTyped,
    ResponseROToJSON,
} from './ResponseRO';

/**
 * 
 * @export
 * @interface AlexaRO
 */
export interface AlexaRO {
    /**
     * 
     * @type {RequestRO}
     * @memberof AlexaRO
     */
    request?: RequestRO;
    /**
     * 
     * @type {ResponseRO}
     * @memberof AlexaRO
     */
    response?: ResponseRO;
    /**
     * 
     * @type {string}
     * @memberof AlexaRO
     */
    version?: string;
    /**
     * 
     * @type {object}
     * @memberof AlexaRO
     */
    session?: object;
    /**
     * 
     * @type {object}
     * @memberof AlexaRO
     */
    context?: object;
}

/**
 * Check if a given object implements the AlexaRO interface.
 */
export function instanceOfAlexaRO(value: object): value is AlexaRO {
    return true;
}

export function AlexaROFromJSON(json: any): AlexaRO {
    return AlexaROFromJSONTyped(json, false);
}

export function AlexaROFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlexaRO {
    if (json == null) {
        return json;
    }
    return {
        
        'request': json['request'] == null ? undefined : RequestROFromJSON(json['request']),
        'response': json['response'] == null ? undefined : ResponseROFromJSON(json['response']),
        'version': json['version'] == null ? undefined : json['version'],
        'session': json['session'] == null ? undefined : json['session'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function AlexaROToJSON(value?: AlexaRO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request': RequestROToJSON(value['request']),
        'response': ResponseROToJSON(value['response']),
        'version': value['version'],
        'session': value['session'],
        'context': value['context'],
    };
}

