/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAttendee
 */
export interface CreateAttendee {
    /**
     * 
     * @type {string}
     * @memberof CreateAttendee
     */
    relID?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAttendee
     */
    userID?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAttendee
     */
    meetupID?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAttendee
     */
    host?: boolean;
}

/**
 * Check if a given object implements the CreateAttendee interface.
 */
export function instanceOfCreateAttendee(value: object): value is CreateAttendee {
    return true;
}

export function CreateAttendeeFromJSON(json: any): CreateAttendee {
    return CreateAttendeeFromJSONTyped(json, false);
}

export function CreateAttendeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAttendee {
    if (json == null) {
        return json;
    }
    return {
        
        'relID': json['relID'] == null ? undefined : json['relID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
        'meetupID': json['meetupID'] == null ? undefined : json['meetupID'],
        'host': json['host'] == null ? undefined : json['host'],
    };
}

export function CreateAttendeeToJSON(value?: CreateAttendee | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'relID': value['relID'],
        'userID': value['userID'],
        'meetupID': value['meetupID'],
        'host': value['host'],
    };
}

