/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateVoting
 */
export interface CreateVoting {
    /**
     * 
     * @type {string}
     * @memberof CreateVoting
     */
    voteid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVoting
     */
    userid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVoting
     */
    meetupid?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt1?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt2?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt3?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt4?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt5?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt6?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVoting
     */
    opt7?: boolean;
}

/**
 * Check if a given object implements the CreateVoting interface.
 */
export function instanceOfCreateVoting(value: object): value is CreateVoting {
    return true;
}

export function CreateVotingFromJSON(json: any): CreateVoting {
    return CreateVotingFromJSONTyped(json, false);
}

export function CreateVotingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVoting {
    if (json == null) {
        return json;
    }
    return {
        
        'voteid': json['voteid'] == null ? undefined : json['voteid'],
        'userid': json['userid'] == null ? undefined : json['userid'],
        'meetupid': json['meetupid'] == null ? undefined : json['meetupid'],
        'opt1': json['opt1'] == null ? undefined : json['opt1'],
        'opt2': json['opt2'] == null ? undefined : json['opt2'],
        'opt3': json['opt3'] == null ? undefined : json['opt3'],
        'opt4': json['opt4'] == null ? undefined : json['opt4'],
        'opt5': json['opt5'] == null ? undefined : json['opt5'],
        'opt6': json['opt6'] == null ? undefined : json['opt6'],
        'opt7': json['opt7'] == null ? undefined : json['opt7'],
    };
}

export function CreateVotingToJSON(value?: CreateVoting | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'voteid': value['voteid'],
        'userid': value['userid'],
        'meetupid': value['meetupid'],
        'opt1': value['opt1'],
        'opt2': value['opt2'],
        'opt3': value['opt3'],
        'opt4': value['opt4'],
        'opt5': value['opt5'],
        'opt6': value['opt6'],
        'opt7': value['opt7'],
    };
}

