/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMeetup
 */
export interface CreateMeetup {
    /**
     * 
     * @type {string}
     * @memberof CreateMeetup
     */
    meetupID?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMeetup
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMeetup
     */
    friends?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMeetup
     */
    option?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMeetup
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateMeetup
     */
    validuntil?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateMeetup
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateMeetup interface.
 */
export function instanceOfCreateMeetup(value: object): value is CreateMeetup {
    return true;
}

export function CreateMeetupFromJSON(json: any): CreateMeetup {
    return CreateMeetupFromJSONTyped(json, false);
}

export function CreateMeetupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMeetup {
    if (json == null) {
        return json;
    }
    return {
        
        'meetupID': json['meetupID'] == null ? undefined : json['meetupID'],
        'title': json['title'] == null ? undefined : json['title'],
        'friends': json['friends'] == null ? undefined : json['friends'],
        'option': json['option'] == null ? undefined : json['option'],
        'location': json['location'] == null ? undefined : json['location'],
        'validuntil': json['validuntil'] == null ? undefined : json['validuntil'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateMeetupToJSON(value?: CreateMeetup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meetupID': value['meetupID'],
        'title': value['title'],
        'friends': value['friends'],
        'option': value['option'],
        'location': value['location'],
        'validuntil': value['validuntil'],
        'description': value['description'],
    };
}

