/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    lastname?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    token?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateUser
     */
    validuntil?: number;
}

/**
 * Check if a given object implements the CreateUser interface.
 */
export function instanceOfCreateUser(value: object): value is CreateUser {
    return true;
}

export function CreateUserFromJSON(json: any): CreateUser {
    return CreateUserFromJSONTyped(json, false);
}

export function CreateUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUser {
    if (json == null) {
        return json;
    }
    return {
        
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'password': json['password'] == null ? undefined : json['password'],
        'email': json['email'] == null ? undefined : json['email'],
        'token': json['token'] == null ? undefined : json['token'],
        'validuntil': json['validuntil'] == null ? undefined : json['validuntil'],
    };
}

export function CreateUserToJSON(value?: CreateUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstname': value['firstname'],
        'lastname': value['lastname'],
        'password': value['password'],
        'email': value['email'],
        'token': value['token'],
        'validuntil': value['validuntil'],
    };
}

