/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Timestamp } from './Timestamp';
import {
    TimestampFromJSON,
    TimestampFromJSONTyped,
    TimestampToJSON,
} from './Timestamp';

/**
 * 
 * @export
 * @interface CreateOptions
 */
export interface CreateOptions {
    /**
     * 
     * @type {string}
     * @memberof CreateOptions
     */
    optionid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOptions
     */
    optionserial?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOptions
     */
    meetupid?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof CreateOptions
     */
    dateandtime?: Timestamp;
}

/**
 * Check if a given object implements the CreateOptions interface.
 */
export function instanceOfCreateOptions(value: object): value is CreateOptions {
    return true;
}

export function CreateOptionsFromJSON(json: any): CreateOptions {
    return CreateOptionsFromJSONTyped(json, false);
}

export function CreateOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'optionid': json['optionid'] == null ? undefined : json['optionid'],
        'optionserial': json['optionserial'] == null ? undefined : json['optionserial'],
        'meetupid': json['meetupid'] == null ? undefined : json['meetupid'],
        'dateandtime': json['dateandtime'] == null ? undefined : TimestampFromJSON(json['dateandtime']),
    };
}

export function CreateOptionsToJSON(value?: CreateOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'optionid': value['optionid'],
        'optionserial': value['optionserial'],
        'meetupid': value['meetupid'],
        'dateandtime': TimestampToJSON(value['dateandtime']),
    };
}

