/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntentRO
 */
export interface IntentRO {
    /**
     * 
     * @type {string}
     * @memberof IntentRO
     */
    name?: string;
}

/**
 * Check if a given object implements the IntentRO interface.
 */
export function instanceOfIntentRO(value: object): value is IntentRO {
    return true;
}

export function IntentROFromJSON(json: any): IntentRO {
    return IntentROFromJSONTyped(json, false);
}

export function IntentROFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntentRO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function IntentROToJSON(value?: IntentRO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

