/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meetupcreate
 */
export interface Meetupcreate {
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    friends?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    place?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    specification?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    timerange?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupcreate
     */
    description?: string;
}

/**
 * Check if a given object implements the Meetupcreate interface.
 */
export function instanceOfMeetupcreate(value: object): value is Meetupcreate {
    return true;
}

export function MeetupcreateFromJSON(json: any): Meetupcreate {
    return MeetupcreateFromJSONTyped(json, false);
}

export function MeetupcreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meetupcreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'friends': json['friends'] == null ? undefined : json['friends'],
        'date': json['date'] == null ? undefined : json['date'],
        'place': json['place'] == null ? undefined : json['place'],
        'specification': json['specification'] == null ? undefined : json['specification'],
        'timerange': json['timerange'] == null ? undefined : json['timerange'],
        'token': json['token'] == null ? undefined : json['token'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function MeetupcreateToJSON(value?: Meetupcreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'friends': value['friends'],
        'date': value['date'],
        'place': value['place'],
        'specification': value['specification'],
        'timerange': value['timerange'],
        'token': value['token'],
        'description': value['description'],
    };
}

