/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meetupedit
 */
export interface Meetupedit {
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    title?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Meetupedit
     */
    friends?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    place?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    specification?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    timerange?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    meetupID?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupedit
     */
    description?: string;
}

/**
 * Check if a given object implements the Meetupedit interface.
 */
export function instanceOfMeetupedit(value: object): value is Meetupedit {
    return true;
}

export function MeetupeditFromJSON(json: any): Meetupedit {
    return MeetupeditFromJSONTyped(json, false);
}

export function MeetupeditFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meetupedit {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'friends': json['friends'] == null ? undefined : json['friends'],
        'date': json['date'] == null ? undefined : json['date'],
        'place': json['place'] == null ? undefined : json['place'],
        'specification': json['specification'] == null ? undefined : json['specification'],
        'timerange': json['timerange'] == null ? undefined : json['timerange'],
        'meetupID': json['meetupID'] == null ? undefined : json['meetupID'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function MeetupeditToJSON(value?: Meetupedit | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'friends': value['friends'],
        'date': value['date'],
        'place': value['place'],
        'specification': value['specification'],
        'timerange': value['timerange'],
        'meetupID': value['meetupID'],
        'userId': value['userId'],
        'description': value['description'],
    };
}

