/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meetupdelete
 */
export interface Meetupdelete {
    /**
     * 
     * @type {string}
     * @memberof Meetupdelete
     */
    userID?: string;
    /**
     * 
     * @type {string}
     * @memberof Meetupdelete
     */
    meetupID?: string;
}

/**
 * Check if a given object implements the Meetupdelete interface.
 */
export function instanceOfMeetupdelete(value: object): value is Meetupdelete {
    return true;
}

export function MeetupdeleteFromJSON(json: any): Meetupdelete {
    return MeetupdeleteFromJSONTyped(json, false);
}

export function MeetupdeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meetupdelete {
    if (json == null) {
        return json;
    }
    return {
        
        'userID': json['userID'] == null ? undefined : json['userID'],
        'meetupID': json['meetupID'] == null ? undefined : json['meetupID'],
    };
}

export function MeetupdeleteToJSON(value?: Meetupdelete | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userID': value['userID'],
        'meetupID': value['meetupID'],
    };
}

