/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputSpeechRO
 */
export interface OutputSpeechRO {
    /**
     * 
     * @type {string}
     * @memberof OutputSpeechRO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OutputSpeechRO
     */
    text?: string;
}

/**
 * Check if a given object implements the OutputSpeechRO interface.
 */
export function instanceOfOutputSpeechRO(value: object): value is OutputSpeechRO {
    return true;
}

export function OutputSpeechROFromJSON(json: any): OutputSpeechRO {
    return OutputSpeechROFromJSONTyped(json, false);
}

export function OutputSpeechROFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputSpeechRO {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function OutputSpeechROToJSON(value?: OutputSpeechRO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'text': value['text'],
    };
}

