/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntentRO } from './IntentRO';
import {
    IntentROFromJSON,
    IntentROFromJSONTyped,
    IntentROToJSON,
} from './IntentRO';

/**
 * 
 * @export
 * @interface RequestRO
 */
export interface RequestRO {
    /**
     * 
     * @type {string}
     * @memberof RequestRO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestRO
     */
    requestId?: string;
    /**
     * 
     * @type {IntentRO}
     * @memberof RequestRO
     */
    intent?: IntentRO;
    /**
     * 
     * @type {string}
     * @memberof RequestRO
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestRO
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the RequestRO interface.
 */
export function instanceOfRequestRO(value: object): value is RequestRO {
    return true;
}

export function RequestROFromJSON(json: any): RequestRO {
    return RequestROFromJSONTyped(json, false);
}

export function RequestROFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRO {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'intent': json['intent'] == null ? undefined : IntentROFromJSON(json['intent']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function RequestROToJSON(value?: RequestRO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'requestId': value['requestId'],
        'intent': IntentROToJSON(value['intent']),
        'locale': value['locale'],
        'timestamp': value['timestamp'],
    };
}

