/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutputSpeechRO } from './OutputSpeechRO';
import {
    OutputSpeechROFromJSON,
    OutputSpeechROFromJSONTyped,
    OutputSpeechROToJSON,
} from './OutputSpeechRO';

/**
 * 
 * @export
 * @interface ResponseRO
 */
export interface ResponseRO {
    /**
     * 
     * @type {OutputSpeechRO}
     * @memberof ResponseRO
     */
    outputSpeech?: OutputSpeechRO;
    /**
     * 
     * @type {boolean}
     * @memberof ResponseRO
     */
    shouldEndSession?: boolean;
}

/**
 * Check if a given object implements the ResponseRO interface.
 */
export function instanceOfResponseRO(value: object): value is ResponseRO {
    return true;
}

export function ResponseROFromJSON(json: any): ResponseRO {
    return ResponseROFromJSONTyped(json, false);
}

export function ResponseROFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseRO {
    if (json == null) {
        return json;
    }
    return {
        
        'outputSpeech': json['outputSpeech'] == null ? undefined : OutputSpeechROFromJSON(json['outputSpeech']),
        'shouldEndSession': json['shouldEndSession'] == null ? undefined : json['shouldEndSession'],
    };
}

export function ResponseROToJSON(value?: ResponseRO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'outputSpeech': OutputSpeechROToJSON(value['outputSpeech']),
        'shouldEndSession': value['shouldEndSession'],
    };
}

