/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendBackToken
 */
export interface SendBackToken {
    /**
     * 
     * @type {string}
     * @memberof SendBackToken
     */
    token?: string;
    /**
     * 
     * @type {number}
     * @memberof SendBackToken
     */
    validInSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof SendBackToken
     */
    userID?: string;
}

/**
 * Check if a given object implements the SendBackToken interface.
 */
export function instanceOfSendBackToken(value: object): value is SendBackToken {
    return true;
}

export function SendBackTokenFromJSON(json: any): SendBackToken {
    return SendBackTokenFromJSONTyped(json, false);
}

export function SendBackTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendBackToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'validInSeconds': json['validInSeconds'] == null ? undefined : json['validInSeconds'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

export function SendBackTokenToJSON(value?: SendBackToken | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'validInSeconds': value['validInSeconds'],
        'userID': value['userID'],
    };
}

