/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Timestamp
 */
export interface Timestamp {
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    nanos?: number;
}

/**
 * Check if a given object implements the Timestamp interface.
 */
export function instanceOfTimestamp(value: object): value is Timestamp {
    return true;
}

export function TimestampFromJSON(json: any): Timestamp {
    return TimestampFromJSONTyped(json, false);
}

export function TimestampFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timestamp {
    if (json == null) {
        return json;
    }
    return {
        
        'nanos': json['nanos'] == null ? undefined : json['nanos'],
    };
}

export function TimestampToJSON(value?: Timestamp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nanos': value['nanos'],
    };
}

