/* tslint:disable */
/* eslint-disable */
/**
 * socialize API
 * socialize API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Userlogin
 */
export interface Userlogin {
    /**
     * 
     * @type {string}
     * @memberof Userlogin
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Userlogin
     */
    password?: string;
}

/**
 * Check if a given object implements the Userlogin interface.
 */
export function instanceOfUserlogin(value: object): value is Userlogin {
    return true;
}

export function UserloginFromJSON(json: any): Userlogin {
    return UserloginFromJSONTyped(json, false);
}

export function UserloginFromJSONTyped(json: any, ignoreDiscriminator: boolean): Userlogin {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserloginToJSON(value?: Userlogin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

